In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("../Datasets/weather_big_data.csv")
df

,City,Temperature,Humidity,Wind Speed,Pressure,Weather,Date
0,Kolkata,40,55,28,1008,Haze,2026-05-07 04:11:15.679396
1,Bangalore,26,92,12,992,Haze,2026-04-26 13:11:15.680668
2,Lucknow,30,49,20,992,Haze,2026-05-07 18:11:15.680668
3,Bangalore,30,47,18,1019,Haze,2026-04-28 17:11:15.680668
4,Delhi,21,52,29,991,Sunny,2026-05-07 17:11:15.680668
...,...,...,...,...,...,...,...
995,Mumbai,24,74,8,1029,Sunny,2026-04-30 17:11:15.691642
996,Bangalore,37,78,9,1026,Sunny,2026-04-12 22:11:15.691642
997,Delhi,23,64,1,1020,Rainy,2026-05-03 06:11:15.691642
998,Chennai,34,30,19,994,Sunny,2026-04-20 22:11:15.691642
999,Mumbai,34,58,23,1006,Thunderstorm,2026-04-23 02:11:15.691642

In [3]:
df.Date = pd.to_datetime(df.Date)

In [4]:
df

,City,Temperature,Humidity,Wind Speed,Pressure,Weather,Date
0,Kolkata,40,55,28,1008,Haze,2026-05-07 04:11:15.679396
1,Bangalore,26,92,12,992,Haze,2026-04-26 13:11:15.680668
2,Lucknow,30,49,20,992,Haze,2026-05-07 18:11:15.680668
3,Bangalore,30,47,18,1019,Haze,2026-04-28 17:11:15.680668
4,Delhi,21,52,29,991,Sunny,2026-05-07 17:11:15.680668
...,...,...,...,...,...,...,...
995,Mumbai,24,74,8,1029,Sunny,2026-04-30 17:11:15.691642
996,Bangalore,37,78,9,1026,Sunny,2026-04-12 22:11:15.691642
997,Delhi,23,64,1,1020,Rainy,2026-05-03 06:11:15.691642
998,Chennai,34,30,19,994,Sunny,2026-04-20 22:11:15.691642
999,Mumbai,34,58,23,1006,Thunderstorm,2026-04-23 02:11:15.691642

In [5]:
df['Date'] = pd.to_datetime(df['Date']).dt.date

In [6]:
df

,City,Temperature,Humidity,Wind Speed,Pressure,Weather,Date
0,Kolkata,40,55,28,1008,Haze,2026-05-07
1,Bangalore,26,92,12,992,Haze,2026-04-26
2,Lucknow,30,49,20,992,Haze,2026-05-07
3,Bangalore,30,47,18,1019,Haze,2026-04-28
4,Delhi,21,52,29,991,Sunny,2026-05-07
...,...,...,...,...,...,...,...
995,Mumbai,24,74,8,1029,Sunny,2026-04-30
996,Bangalore,37,78,9,1026,Sunny,2026-04-12
997,Delhi,23,64,1,1020,Rainy,2026-05-03
998,Chennai,34,30,19,994,Sunny,2026-04-20
999,Mumbai,34,58,23,1006,Thunderstorm,2026-04-23

In [7]:
df['Display_Time'] = pd.to_datetime(df['Date']).dt.strftime('%I:%M %p')

In [8]:
df

,City,Temperature,Humidity,Wind Speed,Pressure,Weather,Date,Display_Time
0,Kolkata,40,55,28,1008,Haze,2026-05-07,12:00 AM
1,Bangalore,26,92,12,992,Haze,2026-04-26,12:00 AM
2,Lucknow,30,49,20,992,Haze,2026-05-07,12:00 AM
3,Bangalore,30,47,18,1019,Haze,2026-04-28,12:00 AM
4,Delhi,21,52,29,991,Sunny,2026-05-07,12:00 AM
...,...,...,...,...,...,...,...,...
995,Mumbai,24,74,8,1029,Sunny,2026-04-30,12:00 AM
996,Bangalore,37,78,9,1026,Sunny,2026-04-12,12:00 AM
997,Delhi,23,64,1,1020,Rainy,2026-05-03,12:00 AM
998,Chennai,34,30,19,994,Sunny,2026-04-20,12:00 AM
999,Mumbai,34,58,23,1006,Thunderstorm,2026-04-23,12:00 AM

In [9]:
df.isnull().sum()

City            0
Temperature     0
Humidity        0
Wind Speed      0
Pressure        0
Weather         0
Date            0
Display_Time    0
dtype: int64

In [10]:
df.dtypes

City            object
Temperature      int64
Humidity         int64
Wind Speed       int64
Pressure         int64
Weather         object
Date            object
Display_Time    object
dtype: object

In [11]:
df['Date'] = pd.to_datetime(df['Date'])

In [12]:
df.dtypes

City                    object
Temperature              int64
Humidity                 int64
Wind Speed               int64
Pressure                 int64
Weather                 object
Date            datetime64[ns]
Display_Time            object
dtype: object

In [13]:
df = df.rename(columns={'Wind Speed':'Wind_Speed'})
df

,City,Temperature,Humidity,Wind_Speed,Pressure,Weather,Date,Display_Time
0,Kolkata,40,55,28,1008,Haze,2026-05-07,12:00 AM
1,Bangalore,26,92,12,992,Haze,2026-04-26,12:00 AM
2,Lucknow,30,49,20,992,Haze,2026-05-07,12:00 AM
3,Bangalore,30,47,18,1019,Haze,2026-04-28,12:00 AM
4,Delhi,21,52,29,991,Sunny,2026-05-07,12:00 AM
...,...,...,...,...,...,...,...,...
995,Mumbai,24,74,8,1029,Sunny,2026-04-30,12:00 AM
996,Bangalore,37,78,9,1026,Sunny,2026-04-12,12:00 AM
997,Delhi,23,64,1,1020,Rainy,2026-05-03,12:00 AM
998,Chennai,34,30,19,994,Sunny,2026-04-20,12:00 AM
999,Mumbai,34,58,23,1006,Thunderstorm,2026-04-23,12:00 AM

In [14]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [15]:
df.City = lable.fit_transform(df.City)

In [16]:
df['Date'] = pd.to_datetime(df['Date'])

df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Weekday'] = df['Date'].dt.weekday

In [17]:
df.drop('Date', axis=1, inplace=True)

In [18]:
df.drop('Display_Time', axis=1, inplace=True)

In [19]:
df

,City,Temperature,Humidity,Wind_Speed,Pressure,Weather,Day,Month,Weekday
0,5,40,55,28,1008,Haze,7,5,3
1,0,26,92,12,992,Haze,26,4,6
2,6,30,49,20,992,Haze,7,5,3
3,0,30,47,18,1019,Haze,28,4,1
4,2,21,52,29,991,Sunny,7,5,3
...,...,...,...,...,...,...,...,...,...
995,7,24,74,8,1029,Sunny,30,4,3
996,0,37,78,9,1026,Sunny,12,4,6
997,2,23,64,1,1020,Rainy,3,5,6
998,1,34,30,19,994,Sunny,20,4,0
999,7,34,58,23,1006,Thunderstorm,23,4,3

In [20]:
df.dtypes

City            int64
Temperature     int64
Humidity        int64
Wind_Speed      int64
Pressure        int64
Weather        object
Day             int32
Month           int32
Weekday         int32
dtype: object

In [21]:
df.Weather = lable.fit_transform(df.Weather)

In [22]:
df

,City,Temperature,Humidity,Wind_Speed,Pressure,Weather,Day,Month,Weekday
0,5,40,55,28,1008,1,7,5,3
1,0,26,92,12,992,1,26,4,6
2,6,30,49,20,992,1,7,5,3
3,0,30,47,18,1019,1,28,4,1
4,2,21,52,29,991,4,7,5,3
...,...,...,...,...,...,...,...,...,...
995,7,24,74,8,1029,4,30,4,3
996,0,37,78,9,1026,4,12,4,6
997,2,23,64,1,1020,3,3,5,6
998,1,34,30,19,994,4,20,4,0
999,7,34,58,23,1006,5,23,4,3

In [23]:
df.isnull().sum()

City           0
Temperature    0
Humidity       0
Wind_Speed     0
Pressure       0
Weather        0
Day            0
Month          0
Weekday        0
dtype: int64

In [29]:
X = df.drop('Weather', axis=1).values

In [30]:
y = df['Weather'].values

In [31]:
X

array([[ 5, 40, 55, ...,  7,  5,  3],
       [ 0, 26, 92, ..., 26,  4,  6],
       [ 6, 30, 49, ...,  7,  5,  3],
       ...,
       [ 2, 23, 64, ...,  3,  5,  6],
       [ 1, 34, 30, ..., 20,  4,  0],
       [ 7, 34, 58, ..., 23,  4,  3]])

In [32]:
y

array([1, 1, 1, 1, 4, 5, 3, 0, 4, 5, 2, 0, 0, 3, 5, 5, 1, 4, 2, 0, 2, 2,
       3, 4, 2, 3, 5, 2, 0, 2, 4, 5, 1, 5, 1, 1, 3, 5, 2, 5, 1, 4, 4, 3,
       3, 3, 1, 5, 4, 4, 3, 4, 2, 0, 0, 5, 4, 2, 2, 5, 1, 4, 0, 4, 0, 1,
       2, 2, 0, 0, 4, 5, 1, 4, 2, 5, 4, 1, 0, 4, 5, 5, 0, 3, 1, 3, 1, 5,
       3, 1, 5, 3, 3, 2, 3, 1, 5, 2, 0, 4, 5, 4, 3, 3, 1, 1, 4, 1, 3, 2,
       1, 5, 2, 3, 0, 5, 0, 3, 0, 2, 4, 4, 1, 0, 3, 2, 5, 5, 1, 2, 0, 4,
       4, 3, 5, 0, 5, 3, 4, 2, 5, 4, 3, 2, 3, 1, 1, 0, 4, 3, 4, 5, 1, 3,
       4, 4, 1, 2, 5, 1, 1, 2, 5, 1, 0, 5, 5, 2, 0, 0, 5, 3, 0, 5, 2, 3,
       1, 2, 5, 5, 1, 0, 4, 1, 1, 1, 0, 3, 1, 0, 1, 0, 4, 2, 5, 2, 4, 5,
       5, 1, 4, 4, 3, 3, 3, 0, 2, 1, 4, 4, 4, 0, 4, 0, 2, 5, 2, 0, 1, 0,
       1, 5, 3, 0, 5, 2, 4, 1, 2, 1, 5, 0, 3, 2, 1, 5, 5, 0, 5, 1, 2, 1,
       1, 2, 4, 4, 3, 3, 4, 0, 1, 0, 1, 2, 3, 5, 4, 5, 0, 1, 3, 3, 2, 0,
       4, 3, 5, 2, 5, 2, 5, 0, 4, 0, 1, 1, 3, 4, 4, 4, 3, 5, 3, 4, 0, 0,
       1, 5, 5, 2, 2, 1, 0, 0, 5, 3, 3, 1, 5, 2, 2, 3, 5, 1, 0, 0, 3, 5,
       3, 0, 0, 1, 3, 1, 0, 4, 0, 4, 0, 4, 3, 2, 0, 2, 4, 5, 3, 2, 2, 2,
       5, 5, 1, 4, 2, 1, 4, 0, 1, 1, 3, 2, 2, 3, 2, 5, 3, 4, 1, 3, 4, 5,
       1, 3, 3, 3, 1, 5, 3, 5, 2, 5, 3, 1, 5, 3, 1, 1, 5, 5, 5, 1, 3, 0,
       5, 5, 3, 3, 4, 2, 1, 4, 4, 2, 2, 0, 5, 2, 4, 0, 3, 1, 4, 5, 1, 3,
       3, 3, 4, 1, 5, 0, 4, 0, 1, 1, 2, 4, 2, 1, 3, 1, 3, 1, 5, 2, 3, 2,
       4, 1, 2, 2, 5, 0, 2, 0, 3, 1, 0, 2, 5, 2, 4, 3, 4, 3, 5, 1, 0, 4,
       5, 2, 3, 0, 3, 2, 2, 3, 0, 4, 0, 4, 0, 0, 1, 0, 2, 1, 4, 4, 3, 5,
       3, 3, 5, 1, 4, 1, 3, 4, 4, 5, 4, 2, 1, 0, 2, 4, 0, 3, 3, 2, 1, 3,
       5, 0, 1, 5, 1, 1, 2, 0, 4, 1, 1, 5, 3, 5, 5, 4, 0, 0, 3, 5, 1, 0,
       2, 0, 4, 4, 1, 2, 4, 4, 2, 5, 2, 4, 3, 1, 3, 5, 1, 5, 1, 3, 3, 0,
       5, 5, 5, 5, 0, 5, 1, 1, 3, 2, 2, 0, 2, 4, 4, 2, 3, 0, 4, 2, 5, 4,
       3, 2, 2, 1, 1, 2, 3, 5, 5, 2, 1, 2, 5, 4, 1, 1, 3, 5, 0, 2, 2, 4,
       2, 1, 1, 4, 0, 3, 2, 5, 1, 3, 5, 5, 1, 0, 3, 1, 3, 1, 5, 5, 3, 5,
       2, 1, 5, 5, 5, 0, 4, 4, 4, 5, 5, 3, 1, 3, 5, 2, 2, 5, 2, 3, 5, 5,
       3, 4, 4, 2, 5, 0, 3, 3, 0, 0, 5, 3, 2, 4, 4, 0, 0, 1, 0, 5, 0, 3,
       1, 0, 0, 5, 4, 1, 4, 0, 4, 1, 3, 4, 4, 4, 3, 1, 0, 2, 5, 2, 2, 3,
       2, 0, 3, 3, 0, 2, 2, 0, 0, 2, 4, 1, 1, 5, 3, 3, 3, 3, 1, 4, 1, 0,
       1, 2, 0, 1, 3, 5, 5, 4, 1, 5, 3, 3, 3, 2, 1, 2, 4, 4, 0, 0, 1, 4,
       5, 1, 2, 0, 0, 2, 5, 0, 4, 2, 0, 1, 5, 5, 1, 5, 0, 5, 2, 2, 2, 1,
       3, 4, 0, 0, 3, 2, 4, 5, 5, 0, 1, 2, 1, 0, 5, 4, 4, 3, 0, 4, 2, 4,
       5, 1, 0, 5, 2, 1, 4, 4, 3, 3, 2, 3, 3, 5, 2, 2, 1, 1, 2, 0, 5, 1,
       3, 4, 0, 5, 5, 0, 2, 5, 2, 4, 3, 2, 2, 2, 3, 3, 2, 1, 0, 4, 1, 2,
       2, 2, 3, 3, 3, 3, 3, 1, 1, 4, 1, 1, 4, 2, 4, 5, 3, 4, 5, 1, 5, 4,
       1, 5, 1, 2, 5, 5, 2, 0, 2, 3, 1, 4, 3, 2, 0, 3, 3, 5, 0, 5, 0, 2,
       5, 4, 1, 1, 4, 1, 3, 0, 2, 1, 1, 2, 0, 2, 2, 0, 2, 4, 3, 5, 0, 0,
       2, 4, 2, 5, 1, 1, 0, 2, 2, 3, 2, 3, 3, 1, 3, 3, 0, 1, 2, 5, 0, 0,
       1, 1, 3, 3, 3, 1, 4, 0, 5, 3, 0, 5, 5, 2, 0, 0, 1, 3, 1, 1, 0, 3,
       1, 1, 3, 5, 1, 4, 3, 3, 3, 1, 5, 4, 2, 0, 5, 2, 0, 3, 0, 4, 5, 4,
       3, 3, 5, 1, 5, 0, 2, 4, 3, 5, 0, 1, 3, 3, 4, 2, 5, 1, 1, 0, 1, 5,
       3, 4, 4, 5, 3, 3, 3, 5, 0, 4, 5, 2, 4, 5, 2, 4, 2, 1, 0, 0, 0, 3,
       4, 2, 1, 2, 0, 1, 3, 0, 4, 5, 0, 2, 1, 5, 1, 4, 1, 4, 5, 2, 3, 5,
       1, 0, 0, 3, 3, 4, 4, 3, 4, 5])

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [55]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, predictions))

0.145

In [57]:
DecisionTreeClassifier()

DecisionTreeClassifier()

In [58]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
model = DecisionTreeClassifier()

In [60]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [61]:
predictions = model.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

Accuracy: 0.15

In [65]:
d={'Actual':y_test,'prediction':predictions}

In [66]:
pd.DataFrame(d)

     Actual  prediction
0         4           4
1         0           3
2         1           2
3         3           4
4         0           5
..      ...         ...
195       2           5
196       0           2
197       2           4
198       4           3
199       1           5

[200 rows x 2 columns]

In [67]:
from sklearn.metrics import r2_score
accuracy = accuracy_score(y_test, predictions)
accuracy*100

15.0

In [70]:
from sklearn.model_selection import cross_val_score
modelcv = DecisionTreeClassifier()
sc = cross_val_score(modelcv,X,y,cv=15,scoring='accuracy')

In [71]:
sc

array([0.2238806 , 0.19402985, 0.08955224, 0.10447761, 0.11940299,
       0.20895522, 0.20895522, 0.1641791 , 0.1641791 , 0.10447761,
       0.13636364, 0.22727273, 0.18181818, 0.09090909, 0.09090909])

In [73]:
sc.mean()*100

np.float64(15.395748530076888)

In [74]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 15.00%

In [75]:
df['Weather'].value_counts()

Weather
1    179
3    176
5    175
2    163
0    154
4    153
Name: count, dtype: int64

In [76]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

In [77]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 17.50%

In [80]:
def weather_condition(row):

    if row['Humidity'] > 80:
        return "Rainy"

    elif row['Temperature'] > 35:
        return "Sunny"

    else:
        return "Cloudy"

In [81]:
df['Weather'] = df.apply(weather_condition, axis=1)

In [82]:
from sklearn.preprocessing import LabelEncoder

le_weather = LabelEncoder()

df['Weather'] = le_weather.fit_transform(df['Weather'])

In [83]:
X = df[['Temperature', 'Humidity', 'Wind_Speed', 'Pressure']]

In [84]:
y = df['Weather']

In [85]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [86]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

DecisionTreeClassifier()

In [87]:
predictions = model.predict(X_test)

In [88]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 100.00%

In [89]:
sample = [[36, 85, 12, 1005]]

In [92]:
sample = [[36, 85, 12, 1005]]

In [93]:
result = model.predict(sample)

print(le_weather.inverse_transform(result))

['Rainy']

In [94]:
sample = [[36, 85, 12, 1005]]

result = model.predict(sample)

print(le_weather.inverse_transform(result))

['Rainy']

In [95]:
import pickle

pickle.dump(model, open('weather_model.pkl', 'wb'))